# Generated by Django 2.0.4 on 2018-05-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessNum', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Playlist')),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45)),
                ('status', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='privilege',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.User'),
        ),
        migrations.AddField(
            model_name='data',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='comment',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Data'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.User'),
        ),
        migrations.AlterUniqueTogether(
            name='privilege',
            unique_together={('id', 'user', 'playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('id', 'playlist')},
        ),
    ]
