# Generated by Django 2.0.4 on 2018-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='picture_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
