# Generated by Django 2.0.4 on 2018-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20180527_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
