# Generated by Django 2.0.4 on 2018-05-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20180527_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Playlist'),
            preserve_default=False,
        ),
    ]
