# Generated by Django 2.0.4 on 2018-05-27 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0004_auto_20180519_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='picture',
        ),
        migrations.AddField(
            model_name='comment',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='part',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.Part'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='data',
            name='playlist',
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('id', 'part')},
        ),
    ]
