# Generated by Django 2.0.4 on 2018-05-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20180527_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='part',
            name='picture',
        ),
    ]
