# Generated by Django 2.0.4 on 2018-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20180528_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
