# Generated by Django 2.0.4 on 2018-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0010_auto_20180530_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='access_num',
            new_name='add_user',
        ),
        migrations.AddField(
            model_name='privilege',
            name='comment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='edit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilege',
            name='read',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
