# Generated by Django 2.0.4 on 2018-05-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_auto_20180531_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='add_user',
            new_name='give_access',
        ),
    ]
