# Generated by Django 2.0.4 on 2018-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0012_auto_20180531_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='comment',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='edit',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='give_access',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='read',
            field=models.NullBooleanField(),
        ),
    ]
