# Generated by Django 2.0.4 on 2018-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0013_auto_20180531_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='comment',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privilege',
            name='edit',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privilege',
            name='give_access',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privilege',
            name='read',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
