# Generated by Django 2.0.4 on 2018-05-31 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0014_auto_20180531_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privilege',
            new_name='Access',
        ),
        migrations.AlterModelTable(
            name='access',
            table='access',
        ),
    ]
